import { Account, Budget, Transaction, UserProfile } from '@/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_guest_01',
  name: 'Raffy Ruiz',
  email: 'invitado@finanzasai.app',
  isGuest: true,
  isPro: false,
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_bank_main',
    name: 'Banco Popular',
    type: 'bank',
    balance: 85000,
    currency: 'DOP',
    color: '#0066B2',
    icon: 'business-outline',
    bankName: 'Banco Popular Dominicano',
  },
  {
    id: 'acc_cash',
    name: 'Efectivo Billetera',
    type: 'cash',
    balance: 12500,
    currency: 'DOP',
    color: '#10B981',
    icon: 'cash-outline',
  },
  {
    id: 'acc_savings',
    name: 'Cuenta Ahorro Reserva',
    type: 'savings',
    balance: 20000,
    currency: 'DOP',
    color: '#8B5CF6',
    icon: 'wallet-outline',
    bankName: 'Banreservas',
  },
  {
    id: 'acc_credit_card',
    name: 'Tarjeta Popular Visa',
    type: 'credit_card',
    balance: -35000, // Saldo adeudado
    balanceUsed: 35000,
    creditLimit: 100000,
    currency: 'DOP',
    color: '#F59E0B',
    icon: 'card-outline',
    billingClosingDay: 15,
    paymentDueDay: 28,
    bankName: 'Banco Popular',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_01',
    type: 'income',
    amount: 102000,
    currency: 'DOP',
    categoryId: 'other_income',
    subcategory: 'Saldo inicial',
    accountId: 'acc_bank_main',
    date: '2026-09-26',
    time: '09:00',
    description: 'Saldo inicial',
    tags: ['#inicial'],
  },
  {
    id: 'tx_02',
    type: 'expense',
    amount: 10500,
    currency: 'DOP',
    categoryId: 'education',
    subcategory: 'Colegio / Escuela',
    accountId: 'acc_credit_card',
    date: '2026-09-26',
    time: '11:30',
    description: 'Colegio nico',
    tags: ['#tarjeta', '#educación'],
    merchant: 'Colegio Santo Domingo',
  },
  {
    id: 'tx_03',
    type: 'expense',
    amount: 100,
    currency: 'DOP',
    categoryId: 'savings_goal',
    subcategory: 'Fondo de Emergencia',
    accountId: 'acc_cash',
    date: '2026-09-26',
    time: '14:15',
    description: 'Meta de Ahorro',
    tags: ['#ahorro'],
  },
  {
    id: 'tx_04',
    type: 'expense',
    amount: 2800,
    currency: 'DOP',
    categoryId: 'food',
    subcategory: 'Supermercado',
    accountId: 'acc_credit_card',
    date: '2026-09-29',
    time: '18:40',
    description: 'Gracias',
    tags: ['#mercado', '#tarjeta'],
    merchant: 'Supermercado Nacional',
  },
  {
    id: 'tx_05',
    type: 'expense',
    amount: 2200,
    currency: 'DOP',
    categoryId: 'transport',
    subcategory: 'Gasolina',
    accountId: 'acc_credit_card',
    date: '2026-09-24',
    time: '08:20',
    description: 'Combustible Shell Churchill',
    tags: ['#gasolina'],
    merchant: 'Estación Shell',
  },
  {
    id: 'tx_06',
    type: 'expense',
    amount: 799,
    currency: 'DOP',
    categoryId: 'entertainment',
    subcategory: 'Streaming (Netflix, Spotify)',
    accountId: 'acc_credit_card',
    date: '2026-09-22',
    time: '03:00',
    description: 'Netflix Premium Familiar',
    tags: ['#recurrente', '#suscripción'],
    isRecurring: true,
  },
  {
    id: 'tx_07',
    type: 'expense',
    amount: 1850,
    currency: 'DOP',
    categoryId: 'home',
    subcategory: 'Electricidad / Luz',
    accountId: 'acc_bank_main',
    date: '2026-09-20',
    time: '10:05',
    description: 'Factura Edeeste',
    tags: ['#servicios', '#hogar'],
    merchant: 'Edeeste',
    isRecurring: true,
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  { id: 'b_food', categoryId: 'food', name: 'Mercado', amount: 15000, period: 'monthly', alertThreshold: 0.8, isRecurring: true, spent: 2800, remaining: 12200, percentage: 19 },
  { id: 'b_subscriptions', categoryId: 'entertainment', name: 'Suscripciones', amount: 888, period: 'monthly', alertThreshold: 0.9, isRecurring: true, spent: 799, remaining: 89, percentage: 90 },
  { id: 'b_transport', categoryId: 'transport', name: 'Transporte', amount: 8000, period: 'monthly', alertThreshold: 0.9, isRecurring: true, spent: 2200, remaining: 5800, percentage: 28 },
  { id: 'b_education', categoryId: 'education', name: 'Educación', amount: 12000, period: 'monthly', alertThreshold: 1.0, isRecurring: true, spent: 10500, remaining: 1500, percentage: 88 },
];

